### PR TITLE
Fix shader compilation for low precision gles hardware and fix cmake includes/linklibs

### PR DESCRIPTION
**Pull request by Memphiz**
as the topic says. Does this still work for you? (and does it look right at all?)

### CODE REVIEW

**Comment by Memphiz** [comment]
Forget about the preset list issue. I am to stupid to drive that v8 500 ps transparency skin ...

**Comment by Memphiz** [comment]
@popcornmix lot of those presets don't do anything for me - is this the same for you too? (Sound sinus wave by Eitraz or BPM by iq for example)

**Comment by popcornmix** [comment]
All presets work on Pi. I had to disable a number of shaders and reduce iteration counts in others from topfs2's desktop GL version as the complexity supported by embedded GL ES 2 is much lower.

It's quite possible that the Wetek is more fussy. Do you get any shader compiler errors to stdout?

**Comment by Memphiz** [comment]
no all compile fine as it seems. I also see some initial screen - so i even might get what they are supposed to do but they just don't move ...

**Comment by popcornmix** [comment]
I've pushed a modified version of this PR - does that work for you?
Rather than making more of the shaders high precision (which is slower if supported and probably unnecessary), I'd prefer to ignore that until we find a reason to enable it.

**Comment by popcornmix** [comment]
Also does https://github.com/popcornmix/screensaver.shadertoy work for you?

**Comment by Memphiz** [comment]
nope it doesn't:

http://pastebin.com/JYVqXaK0

it seems it needs an explicit precision for some vars (those i added in this PR).

**Comment by Memphiz** [comment]
ohhh man this is so annoying on the screensaver its worth ... it brings the same message but i didn't figure out yet where to place the lowp ...

i tried to add 

precision lowp float;
precision lowp vec2;
precision lowp vec3;
precision lowp vec4;
precision lowp sampler2D;

At the beginning of fsSource ... but is this really how its ment to be? Whats going on with those shaders _grr_

**Comment by popcornmix** [comment]
Should include the precision calls from screensaver.shadertoy.

**Comment by Memphiz** [comment]
will do  a new pr asap

**Pull request closed without merging**
